# Generated by Django 6.0.6 on 2026-06-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TattooStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Stil Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, upload_to='styles/', verbose_name='Stil Fotoğrafı')),
                ('price_range', models.CharField(blank=True, max_length=50, verbose_name='Fiyat Aralığı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Dövme Stili',
                'verbose_name_plural': 'Dövme Stilleri',
                'ordering': ['name'],
            },
        ),
    ]
