web: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
release: pip install -r requirements.txt && python manage.py makemigrations --merge && python manage.py migrate --fake-initial && python manage.py collectstatic --noinput && python create_superuser.py
