web: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120 && python manage.py collectstatic --noinput
release: python manage.py migrate && python manage.py collectstatic --noinput && python create_superuser.py
