# Generated by Django 6.0.6 on 2026-06-05 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Fotoğraf')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='styles.tattoostyle', verbose_name='Dövme Stili')),
            ],
            options={
                'verbose_name': 'Galeri Fotoğrafı',
                'verbose_name_plural': 'Galeri Fotoğrafları',
                'ordering': ['-created_at'],
            },
        ),
    ]
